name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Lint structure
        run: |
          python -m compileall addons || true
      - name: Docker Compose
        run: |
          docker compose -f docker/compose.yml up -d
          sleep 30
          curl -f http://localhost:10069/web/login
      - name: Archive addons
        run: tar czf addons.tgz addons
        if: always()
      - uses: actions/upload-artifact@v4
        with:
          name: addons
          path: addons.tgz
